site_name: CS285 â€“ Secure Key Exchange Project
site_description: Java implementation, docs, results, and team credits
site_url: https://shoug-alomran.github.io/CS285-CryptographyProject/

theme:
  name: material
  language: en
  features:
    - content.code.copy
    # tip: add "navigation.expand" if you want groups opened by default
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Introduction: introduction.md
  - Implementation: implementation.md
  - Results: results.md
  - Advantages & Limitations: advantages-limitations.md
  - Conclusion: conclusion.md
  - References: references.md
  - Code:
      - Main: code/main.md
      - Key Exchange: code/keyexchange.md
      - Encryptor: code/encryptor.md
      - Parameters: code/parameters.md
      - Helpers: code/helpers.md
      - Validator: code/validator.md
      - Utils: code/utils.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.attr_list
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
