site_name: CS285 – Diffie–Hellman (Java)
site_url: https://shoug-alomran.github.io/CS285-CryptographyProject
repo_url: https://github.com/Shoug-Alomran/CS285-CryptographyProject
repo_name: CS285-CryptographyProject

theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: deep orange
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - About the Project: about.md
  - Code Overview:
      - Main.java: code/main.md
      - Parameters.java: code/parameters.md
      - KeyExchange.java: code/keyexchange.md
      - Encryptor.java: code/encryptor.md
      - Helpers.java: code/helpers.md
      - Validator.java: code/validator.md
      - Utils.java: code/utils.md
  - Results & Test Cases: results.md
  - Team Contribution: team.md
  - References: references.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.abbr
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
