site_name: CS285 - Secure Key Exchange Project
site_description: Java implementation, docs, results, and team credits
site_url: https://shoug-alomran.github.io/CS285-CryptographyProject/

theme:
  name: material
  language: en
  features:
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Introduction: introduction.md
  - Implementation: implementation.md
  - Results: results.md
  - Advantages & Limitations: advantages-limitations.md
  - Conclusion: conclusion.md
  - References: references.md
  - Team: team.md
  - Code:
      - Main: code/main.md
      - Key Exchange: code/keyexchange.md
      - Encryptor: code/encryptor.md
      - Parameters: code/parameters.md
      - Helpers: code/helpers.md
      - Validator: code/validator.md
      - Utils: code/utils.md
  - Report:
      - View Report: report/report.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css
  - styles/extra.css